spring.application.name=revconnect

spring.datasource.url=jdbc:mysql://localhost:3306/revconnect_db
spring.datasource.username=root
spring.datasource.password=Siddhi@28062004#

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true